name: MSYS2 build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          path-type: strict
          install: make gcc mingw32/mingw-w64-i686-gcc mingw64/mingw-w64-x86_64-gcc

      # Runs a single command using the runners shell
      - name: Make MINGW32
        run: |
          set MSYSTEM=MINGW32
          msys2 -c 'make'

      - name: Make MINGW64
        run: |
          set MSYSTEM=MINGW64
          msys2 -c 'make'

      - name: Make MSYS2
        run: |
          set MSYSTEM=MSYS2
          msys2 -c 'make'
